name:             'Vortex'
url:              'http://www.vortex.es'
markdown:         rdiscount
pygments:         true

baseurl:
permalink:        /:title

authors:
 oxygen:
  name: Oxygen
  display_name: Oxygen
  email: info@oxygen.cat
  web: http://www.vortex.es/

# Server
exclude:          ["LICENSE", "README.md",]
port:             9001

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://www.vortex.es/'
  media: 'assets/img'