name:             'Vortex'
url:              'http://www.vortex.es'
markdown:         rdiscount
pygments:         true

baseurl:
permalink:        /:title

authors:
 vortex:
  name: Vortex
  display_name: Vortex
  email: info@vortex.es
  web: http://www.vortex.es/
 gil:
  name: Gil
  display_name: Gil
  email: gil@vortex.es
  web: http://www.vortex.es/

# Server
exclude:          ["LICENSE", "README.md",]
port:             4000

# Prose
prose:
  rooturl: "_posts"
  siteurl: "http://vortex-es.github.io/"
  media: "assets/img"
  metadata:
    _posts/ask-gil:
      - name: "title"
        field:
          element: "text"
          label: "title"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "gil-faq"
              value: "gil-faq"
              selected: "gil-faq"
      - name: "slug"
        field:
          element: "text"
          label: "slug"
          value: ""
      - name: "categories"
        field:
          element: "hidden"
          value: "ask-gil"
      - name: "meta"
        field:
          element: "text"
          label: "Meta title"
          value: ""
      - name: "excerpt"
        field:
          element: "text"
          label: "excerpt"
          value: ""
      - name: "author"
        field:
          element: "select"
          label: "Who are you dude?"
          placeholder: "Default"
          options:
            - name: "gil"
              value: "gil"
              selected: "gil"
      - name: "keywords"
        field:
          element: "text"
          label: "Meta keywords"
          value: ""