name:             'Vortex'
url:              'http://www.vortex.es'
markdown:         rdiscount
pygments:         true

baseurl:
permalink:        /:title

authors:
 vortex:
  name: Vortex
  display_name: Vortex
  email: info@vortex.es
  web: http://www.vortex.es/
 gil:
  name: Gil
  display_name: Gil
  email: gil@vortex.es
  web: http://www.vortex.es/

# Server
exclude:          ["LICENSE", "README.md",]
port:             4000

# Prose
prose:
  rooturl: "_posts"
  siteurl: "http://www.vortex.es/"
  media: "assets/img"
  metadata:
   _posts/ask-gil:
    - name: "title"
        field:
          element: "text"
          label: "title"
          value: ""
    - name: "layout"
        field:
          element: "select"
          label: "Select a layout"
          placeholder: "Default"
          options:
            - name: "gil-faq"
              value: "gil-faq"
          selected: "gil-faq"